#Config file for declaring custom actions'parameters. The parameters have been listed here in alphabetical order (A-Z).

#GPIOS used in the project. Feel free to change in case.
Gpios:
  AIY_indicator:
    - 25
  assistant_indicators:
    - 05
    - 06
  ir:
    - 17
  picontrol:
    - 12
    - 13
    - 24
  pushbutton_trigger:
    - 22
  servo:
    - 27
  stopbutton_music_AIY_pushbutton:
    - 23


#Text to speech conversation
Speech:
  Voice_Gender: 'Female'

#Custom wakeword On/Off.
#To enable custom wakeword, change status to Enabled and restart the assistant.
Wakewords:
  Custom_Wakeword: 'Disabled'
  Custom_wakeword_models:
    - '/home/pi/Assistants-Pi/Google-Assistant/src/resources/alexa.umdl'
    - '/home/pi/Assistants-Pi/Google-Assistant/src/resources/snowboy.umdl'
